//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppTestPagedList.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Action
    {
        public int id { get; set; }
        public string ActionTime { get; set; }
        public string DateSystem { get; set; }
        public string Browser { get; set; }
        public string Device { get; set; }
        public string IP_Address { get; set; }
        public string HostName { get; set; }
        public string Country { get; set; }
    }
}
