//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppTestPagedList.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Action
    {
        public int id { get; set; }
        public string ActionTime { get; set; }
        public string DateSystem { get; set; }
        public string Browser { get; set; }
        public string Device { get; set; }
        public string IP_Address { get; set; }
        public string HostName { get; set; }
        public string Status { get; set; }
        public string Country { get; set; }
        public string countryCode { get; set; }
        public string region { get; set; }
        public string regionName { get; set; }
        public string city { get; set; }
        public string zip { get; set; }
        public string lat { get; set; }
        public string lon { get; set; }
        public string timezone { get; set; }
        public string isp { get; set; }
        public string org { get; set; }
        public string asn { get; set; }
        public string query { get; set; }
        public string district { get; set; }
        public string reverse { get; set; }
        public string mobile { get; set; }
        public string proxy { get; set; }
    }
}
